safe:        false
url: http://127.0.0.1:4000
baseurl: 
url: //themiurgo.github.io/website

source:      .
destination: ./_site

future:      true
lsi:         false
highliter:   pygments
markdown:    kramdown
permalink:   none

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

home:
  news_limit: 5
  publications_limit: 4

authors:
  alima:
    name: 'Antonio'
    surname: 'Lima'
    site: 'http://themiurgo.github.io/website'
  lrossi:
    name: 'Luca'
    surname: 'Rossi'
    site: 'https://blextar.github.io/luca-rossi/'
  mmusolesi:
    name: 'Mirco'
    surname: 'Musolesi'
    site: 'https://www.mircomusolesi.org/'
  vpejovic:
    name: 'Veljko'
    surname: 'Pejovic'
    site: "http://lrss.fri.uni-lj.si/Veljko/"
  mdedomenico:
    name: 'Manlio'
    surname: 'De Domenico'
    site: 'https://comunelab.fbk.eu/manlio/index.php'
  vcarchiolo:
    name: 'Vincenza'
    surname: 'Carchiolo'
    site: 'http://www.diit.unict.it/users/carchiol/'
  gmangioni:
    name: 'Giuseppe'
    surname: 'Mangioni'
    site: 'www.diit.unict.it/users/gmangioni'
  pmougel:
    name: 'Paul'
    surname: 'Mougel'
    site: 'https://twitter.com/paul_mougel?lang=en'
  mgonzalez:
    name: 'Marta'
    surname: 'González'
    site: 'http://humnetlab.berkeley.edu/'
  scolak:
    name: 'Serdar'
    surname: 'Çolak'
    site: 'https://scholar.google.com/citations?user=6wfuc1UAAAAJ&hl=en'
  mdenadai:
    name: 'Marco'
    surname: 'De Nadai'
    site: 'https://www.marcodena.it/'
  acardoso:
    name: 'Ângelo'
    surname: 'Cardoso'
    site: 'https://scholar.google.com/citations?user=Jk2qAioAAAAJ&hl=en'
  blepri:
    name: 'Bruno'
    surname: 'Lepri'
    site: 'https://scholar.google.com/citations?user=zN5RTZcAAAAJ&hl=en'
  noliver:
    name: 'Nuria'
    surname: 'Oliver'
    site: 'http://www.nuriaoliver.com/'


defaults:
  -
    scope:
      path: ""
    values:
      "hidden": false
